---
apache_listen_port: 80
apache_daemon: apache2

apache_server_root: /etc/apache2
apache_conf_path: /etc/apache2

apache_packages:
  - apache2
  - apache2-mpm-prefork
  - apache2-utils
  - apache2-bin

apache_mods_enabled:
  - proxy.conf
  - proxy.load
  - proxy_http.load

apache_ports_configuration_items:
  - {
    regexp: "^Listen ",
    line: "Listen {{ apache_listen_port }}"
  }

apache_create_vhosts: true

apache_vhosts:
  - { servername: "{{ ansible_fqdn }}", serveradmin: "web@{{ ansible_fqdn }}", ip: "{{ myip }}", documentroot: "/var/www/html" }
